### ISSUE TITLE
Update version of request dependency due to ReDoS vulnerability

### ISSUE THREAD

**Issue by snowinferno** [skoranga/node-curlnsave#4]
Version 2.72 of [request](https://github.com/request/request/blob/v2.72.1/package.json#L44) relies on a [vulnerable version of tough-cookie](https://nodesecurity.io/advisories/130).
To fix the problem, upgrade the dependency to request 2.74 or newer.

**Comment by skoranga** [comment]
Published the latest version (`curlnsave@0.1.6`) with `^2.72` as dependency. This will pick the latest `request` dependency.
